FROM eclipse-temurin:17

LABEL mentainer="javaguides.net@gmail.com"

WORKDIR /app

COPY targer/springboot-docker-demo-0.0.10-SNAPSHOT.jar /app/springboot-docker-demo.jar

ENTRYPOINT["java","-jar","springboot-docker-demo.jar"]